# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="robbyrussell"
#ZSH_THEME="juanghurtado"
#ZSH_THEME="tjkirch-jslu"
ZSH_THEME="powerlevel9k/powerlevel9k"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(osx git node npm nvm tmux rails rvm ruby vagrant brew sudo zsh-syntax-highlighting history-substring-search autosuggestions)

source $ZSH/oh-my-zsh.sh

# Setup zsh-autosuggestions
#source /Users/jslu/.oh-my-zsh/custom/plugins/autosuggestions/autosuggestions.zsh

# Enable autosuggestions automatically
zle-line-init() {
    zle autosuggest-start
}

zle -N zle-line-init

# use ctrl+t to toggle autosuggestions(hopefully this wont be needed as
# zsh-autosuggestions is designed to be unobtrusive)
bindkey '^T' autosuggest-toggle


# Setup history-substring-search
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down


# Customize to your needs...
export PATH=/Users/jslu/.rvm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin:/Library/Frameworks/JRuby.framework/Versions/Current/bin:~/bin:/Library/Frameworks/JRuby.framework/Versions/Current/bin:~/bin:$PATH

## by jslu
fpath=(/usr/local/share/zsh-completions $HOME/.zsh/func $fpath)
typeset -U fpath

eval "$(fasd --init auto)"

# Explicitly specify the EDITOR to be my favorite one
export EDITOR=vim
# Set the Homebrew cask linking to be in /Applications folder
export HOMEBREW_CASK_OPTS="--appdir=/Applications"


# Joe's own aliases
alias cask="brew cask"
alias diff="colordiff"

source "`brew --prefix`/etc/grc.bashrc"

export HOMEBREW_GITHUB_API_TOKEN="11d20dab98d4b70b93187d1f09a57d8adaf15225"

# Look up API from command line
# Usage example: $ dash ruby:FileUtil
function dash() {
  open "dash://$*"
}


## Settings for powerlevel9k theme
POWERLEVEL9K_MODE='awesome-fontconfig'
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context os_icon_joined dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status background_jobs_joined rvm history time)

# enable the vcs segment in general
#POWERLEVEL9K_SHOW_CHANGESET=true
#POWERLEVEL9K_CHANGESET_HASH_LENGTH=6

POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"
POWERLEVEL9K_SHORTEN_DIR_LENGTH=3

POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND="237"
POWERLEVEL9K_OS_ICON_BACKGROUND="237"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="249"
POWERLEVEL9K_DIR_HOME_FOREGROUND="249"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="249"
POWERLEVEL9K_NVM_VISUAL_IDENTIFIER_COLOR="green"
POWERLEVEL9K_RVM_VISUAL_IDENTIFIER_COLOR="red"

POWERLEVEL9K_PROMPT_ON_NEWLINE=true


## Settings for rvm (ruby) & nvm (node.js)
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm



export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
